CREATE TABLE HABITAT(
   id COUNTER,
   TITLE VARCHAR(100),
   IMG VARCHAR(250),
   IMG2 VARCHAR(250),
   DESCRIPTION TEXT,
   PRIMARY KEY(id)
);

CREATE TABLE MISSION(
   ID COUNTER,
   NAME VARCHAR(50),
   LOGO VARCHAR(150),
   DESCRIPTION TEXT,
   PRIMARY KEY(ID)
);

CREATE TABLE PRESTATION(
   ID COUNTER,
   NAME VARCHAR(50),
   LOGO VARCHAR(150),
   DESCRIPTION TEXT,
   PRIMARY KEY(ID)
);

CREATE TABLE ALIMENTATION(
   ID COUNTER,
   NAME VARCHAR(50),
   DESCRIPTION TEXT,
   QUANTITE VARCHAR(250),
   PRIMARY KEY(ID)
);

CREATE TABLE _USER(
   ID COUNTER,
   NAME VARCHAR(150),
   ROLE VARCHAR(50),
   EMAIL VARCHAR(150),
   PASSWORD VARCHAR(250),
   PRIMARY KEY(ID)
);

CREATE TABLE ANIMAUX(
   ID COUNTER,
   IMG VARCHAR(150),
   IMG2 VARCHAR(150),
   TITLE VARCHAR(50),
   DESCRIPTION TEXT,
   SANTE VARCHAR(250),
   SOIN TEXT,
   ID_1 INT NOT NULL,
   id_2 INT NOT NULL,
   PRIMARY KEY(ID),
   FOREIGN KEY(ID_1) REFERENCES ALIMENTATION(ID),
   FOREIGN KEY(id_2) REFERENCES HABITAT(id)
);

CREATE TABLE CARE(
   ID INT,
   ID_1 INT,
   PRIMARY KEY(ID, ID_1),
   FOREIGN KEY(ID) REFERENCES ANIMAUX(ID),
   FOREIGN KEY(ID_1) REFERENCES _USER(ID)
);
